name: calleros-portfolio
services:
  dev:
    image: node:22-alpine
    working_dir: /app
    tty: true
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
      - TZ=America/Tijuana
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: sh -c "npm ci && npm run dev -- --host --port 4321"

  preview:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - TZ=America/Tijuana
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: sh -c "npm ci && npm run build && npm run preview -- --host --port 4321"

  build:
    image: node:22-alpine
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: sh -c "npm ci && npm run build"

  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "8080:80"
    depends_on:
      - build

volumes:
  node_modules:
