name: ci

on:
  pull_request:
    branches: [development, main]
  push:
    branches: [development]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest
    timeout-minutes: 25

    # Browsers preinstalled for your pinned Playwright 1.55.0
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      options: --ipc=host   # run as root (default) so checkout can write

    env:
      CI: 'true'
      BASE_URL: http://127.0.0.1:4321
      HOME: /root            # <-- fixes Firefox launch under root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build (production)
        run: npm run build

      # Playwright will start the server via your playwright.config.ts webServer
      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright HTML report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload traces (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
          retention-days: 7
