name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build (Node adapter for CI)
        env:
          ASTRO_PREVIEW: "1"
        run: npm run build

      - name: Start Astro preview (SSR) and wait
        env:
          ASTRO_PREVIEW: "1"
        run: |
          npx astro preview --port 4321 & \
          npx --yes wait-on http://127.0.0.1:4321

      - name: Run Playwright tests
        env:
          BASE_URL: http://127.0.0.1:4321
        run: npx playwright test

      - name: Upload HTML report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload traces (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
          retention-days: 7
